export interface TwentyOneQuestionsState {
  phase: "playing" | "questionComplete" | "gameEnd";
  currentQuestionIndex: number;
  currentQuestion: string;
  questionIds: number[]; // IDs of selected questions (from the 100 question list)
  playerReady: {
    [playerId: string]: boolean; // Whether each player has clicked "next"
  };
  totalQuestions: number; // Total number of questions to ask (default 21)
  completedQuestions: number; // Number of questions completed
  players: string[]; // Player IDs
}

export interface TwentyOneQuestionsConfig {
  totalQuestions?: number; // Default 21
}

// All 100 ice breaker questions
export const ICE_BREAKER_QUESTIONS = [
  "Where are you from originally?",
  "How's your week been?",
  "What have you been up to lately?",
  "What do you usually do for fun?",
  "What's your go-to way to spend a weekend?",
  "What's something you're into right now?",
  "What's a show you're watching?",
  "What's a movie you've seen recently?",
  "What kind of music do you listen to?",
  "What's your favorite artist right now?",
  "Any songs on repeat lately?",
  "What's your favorite food?",
  "What's your go-to drink order?",
  "Coffee or tea?",
  "What's your favorite fast food spot?",
  "What's your favorite restaurant in your area?",
  "Do you cook at all?",
  "What's your go-to snack?",
  "Sweet or salty?",
  "What's the best meal you've had recently?",
  "Are you more morning or night?",
  "What's your sleep schedule like (realistically)?",
  "Are you a planner or last-minute person?",
  "What's something you're good at?",
  "What's something you want to get better at?",
  "What's a hobby you've tried or want to try?",
  "What do you usually do after a long day?",
  "What's something that helps you de-stress?",
  "Do you like staying in or going out more?",
  "What's your ideal day off?",
  "What's your favorite season?",
  "Summer or winter?",
  "Do you like the city or more quiet places?",
  "Beaches or mountains?",
  "What's the best place you've been?",
  "Where do you want to travel?",
  "Window seat or aisle seat?",
  "Are you good with directions?",
  "What's your favorite thing about where you live?",
  "What's a place you'd move to if you could?",
  "Are you more introvert or extrovert?",
  "Do you like meeting new people?",
  "What's your pet peeve?",
  "What's something that instantly puts you in a good mood?",
  "What's something you could talk about for hours?",
  "What's something you've learned recently?",
  "What's a random skill you have?",
  "What's something you wish you knew sooner?",
  "What's something you're looking forward to?",
  "What's been the highlight of your month?",
  "Do you play any sports or games?",
  "Do you go to the gym or do any workouts?",
  "What's your favorite sport to watch?",
  "Are you into video games?",
  "What games do you play?",
  "What's a game you'll never get tired of?",
  "Do you prefer multiplayer or solo games?",
  "Any hobbies you had as a kid that you still like?",
  "What's something you were obsessed with growing up?",
  "What's your favorite way to spend time with friends?",
  "Are you in school or working right now?",
  "What are you studying / what do you do?",
  "Do you like it?",
  "What made you choose that?",
  "What's the best part about it?",
  "What's the most annoying part?",
  "What's something you want to do in the future?",
  "What's a job you think would be fun?",
  "What's a job you'd never want?",
  "What's a skill you think everyone should have?",
  "Do you have any siblings?",
  "Do you have pets?",
  "What's your pet like?",
  "Are you more a dog person or cat person?",
  "What's your favorite holiday?",
  "Do you have any traditions you like?",
  "What's your birthday season vibe—do you like birthdays?",
  "What's something small you're grateful for lately?",
  "What's something you're proud of?",
  "What's something you're working on personally?",
  "What's your favorite app (besides the obvious ones)?",
  "What's your usual social media?",
  "Do you prefer texting or calling?",
  "Are you more pictures or words?",
  "Do you like taking photos?",
  "What's your camera roll mostly?",
  "What's your favorite YouTube/TikTok type of content?",
  "What's a creator you like?",
  "What's something you've been learning online?",
  "What's your favorite way to waste time?",
  "What's your go-to outfit vibe?",
  "Do you care about fashion or just comfort?",
  "What's a trend you actually like?",
  "What's a trend you don't get?",
  "What's your favorite type of weather?",
  "What's your ideal time to go out?",
  "What's your go-to place to hang out?",
  "What's something you want to do more this year?",
  "What's something you want to do less this year?",
  "What's one thing you're trying to improve right now?"
];

